import {allowedHumanSignalOrigins as configuredHumanOrigins,requireHumanSignalOrigin as validateHumanOrigin} from "./lib/human-signal-origin.mjs";
import {agencyGraph} from "./lib/agency-graph.mjs";
import {CheckpointWorker} from "./lib/checkpoint-worker.mjs";
import {AccountStateDatabase, transactionalResponse} from "./lib/account-state-postgres.mjs";
import { BackupWorker } from "./lib/backup-worker.mjs";
import { PohaDatabase, serviceSigningBytes } from "./lib/poha-postgres.mjs";
import { DISCLOSURE_POLICY_VERSION } from "./lib/poha-disclosure.mjs";
import { readJson, writeJson } from "./lib/durable-json.mjs";
import http from "node:http";
import {humanSignalReleaseReadiness} from './lib/human-signal-release.mjs';
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { fileURLToPath } from "node:url";
import { Connection, Keypair, PublicKey, Transaction, TransactionInstruction, sendAndConfirmTransaction, clusterApiUrl } from "@solana/web3.js";
import { createMint, getOrCreateAssociatedTokenAccount, mintTo, getMint, setAuthority, AuthorityType } from "@solana/spl-token";
import { createV1, findMetadataPda, mplTokenMetadata, TokenStandard } from "@metaplex-foundation/mpl-token-metadata";
import { keypairIdentity, percentAmount, publicKey as umiPublicKey } from "@metaplex-foundation/umi";
import { createUmi } from "@metaplex-foundation/umi-bundle-defaults";
import { normalizeContribution, contributionDigest, contributionId, publicContribution, reputationTable } from "./lib/human-signal.mjs";
import { createWalletChallenge, verifySolanaMessage, newSession, hashSessionToken, isSessionValid, profileIdForWallet, utcDay, nextStreak, deriveRoles, trustScore, MAX_TRUST_CONNECTIONS } from "./lib/human-signal-network.mjs";
import { calculateMiningRate, newMiningSession, applyClaim, publicMiningSession, PIONEER_COHORT_SIZE } from "./lib/signal-mining.mjs";
import { resourceContributionScore, recordResourceHeartbeat } from "./lib/resource-mining.mjs";
import { createNodeJob, publicNodeJob, verifyNodeJob, jobCooldownRemaining } from "./lib/node-jobs.mjs";
import { miningReserveState, rateUnits } from "./lib/mining-economics.mjs";
import { hashIdentity, normalizePhone, newOauthState, isOauthStateValid, publicHumanProof } from "./lib/human-proof.mjs";
import { appendCoreEvent, verifyEventChain, coreStateRoot, trustStateRoot, registerCoreApp, recordAppUtility, networkHealth } from "./lib/human-signal-core.mjs";
import { guardDirectHumanMutation, enforcementStatus } from "./lib/human-signal-core-v1-alpha.mjs";
import { bindAgent, createSignedDelegation, revokeSignedRecord, inspectAction } from "./lib/poha-v1.mjs";
import { registerAgent, grantDelegation, revokeDelegation, agencyForOwner } from "./lib/human-agency.mjs";
import { publicPioneerSupport, referralBoost } from "./lib/pioneer-support.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, "dist");
const DATA_DIR = process.env.COHIBA_DATA_DIR || "/data";
const port = Number(process.env.PORT || 8080);
const DESTINATION = new PublicKey("pTEH7pYratL14VFPQ9i5JMvPYDCpCQ773cHQZ3DdW3t");
const DECIMALS = 9;
const SUPPLY = 1_000_000_000n * 10n ** 9n;
const PUBLIC_BASE_URL = process.env.PUBLIC_BASE_URL || "https://cohiba-web-live-production.up.railway.app";
const CANONICAL_PUBLIC_ORIGIN = "https://cohibameme.site";
const METADATA_URI = `${PUBLIC_BASE_URL.replace(/\/$/,"")}/token-metadata.json`;
const MAINNET_MIN_SOL = 0.03;
const HSC_MEMO_PROGRAM=new PublicKey("MemoSq4gqABAXKb96QN?"